### ISSUE TITLE
Refactor all tests

### ISSUE THREAD

**Issue by Eldon-Chung** [CS2103JAN2018-F09-B3/main#167]
There are quite some tests which are still testing based on the AddressBook context. These include:
* system tests
* command parser tests
* storage tests
* command tests

Most of these are test case names, or XmlData, and some are system tests that have been previously removed due to enhancements that have changed their behaviour. E.g. FindCommand.

Some major data alteration, variable renaming, reinstating and fixing test cases is necessary.
Also some new code that has been added has not been sufficiently tests. Test cases should be added to increase coverage.

**Comment by ewaldhew** [comment]
Close if done
