### ISSUE TITLE
Wrapper class needed to combine FetchUtil and JsonUtil

### ISSUE THREAD

**Issue by laichengyu** [CS2103JAN2018-F09-B3/main#50]
* Fetching data from 3rd party APIs currently require the caller to use FetchUtil and JsonUtil separately.
* Should have a wrapper class that does both JSON fetching and JSON deserialising so that other classes only need to import and use a single class.

**Comment by ewaldhew** [comment]
This isn't needed anymore, right?

**Comment by laichengyu** [comment]
Yep not needed anymore.
