### ISSUE TITLE
FetchUtil: Typo in Logger parameters

### ISSUE THREAD

**Issue by laichengyu** [CS2103JAN2018-F09-B3/main#51]
#39 

https://github.com/laichengyu/main/blob/3b861a850912b3efb4be720600f44d8b6e0fc7ad/src/main/java/seedu/address/commons/util/FetchUtil.java#L20

**Comment by ewaldhew** [comment]
Is this done?

**Comment by laichengyu** [comment]
This is done in my latest PR for sync command (not merged yet)
